### ISSUE TITLE
Bug in chaosk8s.statefulset.probes.statefulset_fully_available: V1StatefulSetStatus' object has no attribute 'unavailable_replicas'

### ISSUE THREAD

**Issue by 0xf10413** [chaostoolkit/chaostoolkit-kubernetes#112]
Hi !

While testing the lib against statefulsets, i encountered an issue.
With the following probe:
```
{
     "name": "all-our-microservices-should-be-healthy",
     "type": "probe",
     "tolerance": true,
     "timeout": 5,
     "provider": {
         "type": "python",
         "module": "chaosk8s.statefulset.probes",
         "func": "statefulset_fully_available",
         "arguments": {
             "name": "echo-server"
         }
     }
}
```

My experiment fails with the following error:
```[2020-12-01 19:52:09 INFO] Steady state hypothesis: Verifying service remains healthy
[2020-12-01 19:52:09 INFO] Probe: all-our-microservices-should-be-healthy
[2020-12-01 19:52:09 ERROR]   => failed: AttributeError: 'V1StatefulSetStatus' object has no attribute 'unavailable_replicas'
```

This looks like an internal issue in chaostoolkit-kubernetes, since unavailableReplicas is not a valid field for [StatefulSetStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#statefulsetstatus-v1-apps), while it exists for [DeploymentStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#deploymentstatus-v1-apps).

Here's a simple reproducer:
[experiment.zip](https://github.com/chaostoolkit/chaostoolkit-kubernetes/files/5624816/experiment.zip)

<details><summary>And here is the full stacktrace</summary>

```
Traceback (most recent call last):
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaosk8s/statefulset/probes.py", line 111, in statefulset_fully_available
        if _statefulset_readiness_has_state(
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaosk8s/statefulset/probes.py", line 64, in _statefulset_readiness_has_state
        u=status.unavailable_replicas))
    AttributeError: 'V1StatefulSetStatus' object has no attribute 'unavailable_replicas'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaoslib/activity.py", line 227, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaosk8s/statefulset/probes.py", line 111, in statefulset_fully_available
        if _statefulset_readiness_has_state(
      File "/home/flo/documents/code/chaos-server/venv/lib/python3.8/site-packages/chaosk8s/statefulset/probes.py", line 64, in _statefulset_readiness_has_state
        u=status.unavailable_replicas))
    chaoslib.exceptions.ActivityFailed: AttributeError: 'V1StatefulSetStatus' object has no attribute 'unavailable_replicas'
```
</details>

I tried to look around for existing open issues. #59 was a close one, but it was flagged as an "enhancement", i.e. adding a missing feature.

Here, I suspect it's more of a bug. But please advice if I were to be mistaken.

Cheers!

EDIT: I should have the latest versions of everything, but just in case:
```
$ pip freeze | grep chaos
chaostoolkit==1.7.1
chaostoolkit-kubernetes==0.25.0
chaostoolkit-lib==1.15.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ari06xx** [comment]
Same issue with
chaostoolkit                   1.9.0
chaostoolkit-kubernetes        0.25.1

**Comment by hamdymoussa** [comment]
Same issue with chaos, version 1.9.6
