### ISSUE TITLE
terminate_pods with tries to match labels even when one is not set.

### ISSUE THREAD

**Issue by rdrgmnzs** [chaostoolkit/chaostoolkit-kubernetes#21]
When using terminate_pods and defining only a NS, it will also try to match the labes to none:

Config:
```
method:
- name: terminate-pods
  type: action
  provider:
    func: terminate_pods
    module: chaosk8s.pod.actions
    type: python
    arguments:
      ns: 'myapp'
```

Error log:
```
[2018-10-05 03:05:15 DEBUG] Using Kubernetes context: Default
[2018-10-05 03:05:15 DEBUG] Found 0 pods labelled 'None'
[2018-10-05 03:05:15 DEBUG] Activity failed
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/chaoslib/provider/python.py", line 50, in run_python_activity
        return func(**arguments)
      File "/usr/local/lib/python3.5/dist-packages/chaosk8s/pod/actions.py", line 58, in terminate_pods
        pods = [pods[0]]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/chaoslib/activity.py", line 218, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/usr/local/lib/python3.5/dist-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        sys.exc_info()[2])
      File "/usr/local/lib/python3.5/dist-packages/chaoslib/provider/python.py", line 50, in run_python_activity
        return func(**arguments)
      File "/usr/local/lib/python3.5/dist-packages/chaosk8s/pod/actions.py", line 58, in terminate_pods
        pods = [pods[0]]
    chaoslib.exceptions.ActivityFailed: IndexError: list index out of range
[2018-10-05 03:05:15 ERROR]   => failed: IndexError: list index out of range
```

Setting a label_selector however, gets things to work.

**Comment by Lawouach** [comment]
Good catch! Thanks.

**Comment by Lawouach** [comment]
That was a good one to catch @rdrgmnzs as it impacted all sort of calls in the code. The problem is that underlying Kubernetes client won't treat  `None` as you would hope but rather serialize everything to string.

**Comment by rdrgmnzs** [comment]
@Lawouach thank you for the fix and the quick turn around!
