### ISSUE TITLE
chaos discover  invalid syntax

### ISSUE THREAD

**Issue by purpletech77** [chaostoolkit/chaostoolkit-kubernetes#33]
$ chaos discover chaostoolkit-kubernetes --no-install
Traceback (most recent call last):
  File "/usr/bin/chaos", line 6, in <module>
    from chaostoolkit.__main__ import cli
  File "/usr/lib/python2.7/site-packages/chaostoolkit/__main__.py", line 20
    def run(report_path: str, dry: bool, path: str):
                       ^
SyntaxError: invalid syntax

**Comment by purpletech77** [comment]
passed with new conda python3
