### ISSUE TITLE
CHAOSTOOLKIT_IN_POD env variable not working in kubernetes

### ISSUE THREAD

**Issue by shyimo** [chaostoolkit/chaostoolkit-kubernetes#79]
Looks like exception is thrown when using the `CHAOSTOOLKIT_IN_POD` environment variable in the kubernetes:

stack trace from the logs:

```
Traceback (most recent call last):
  File "/usr/local/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/chaostoolkit/cli.py", line 106, in run
    experiment = load_experiment(
  File "/usr/local/lib/python3.8/site-packages/chaoslib/loader.py", line 96, in load_experiment
    parsed = parse_experiment_from_file(experiment_source)
  File "/usr/local/lib/python3.8/site-packages/chaoslib/loader.py", line 38, in parse_experiment_from_file
    return json.load(f)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 8 column 3 (char 213)
```

**Comment by Lawouach** [comment]
Hi there,

Since you closed it, I assume it wasn't a problem? Feel free to let us know otherwise
